---

env:
    DEST_BRANCH: "master"
    GOPATH: "/var/tmp/go"
    GOBIN: "${GOPATH}/bin"
    GOCACHE: "${GOPATH}/cache"
    GOSRC: "${GOPATH}/src/github.com/containers/podman"
    CIRRUS_WORKING_DIR: "${GOPATH}/src/github.com/containers/podman-py"
    SCRIPT_BASE: "./contrib/cirrus"
    CIRRUS_SHELL: "/bin/bash"
    HOME: "/root"  # not set by default

    ####
    #### Cache-image names to test with (double-quotes around names are critical)
    ####
    FEDORA_NAME: "fedora-34"
    PRIOR_FEDORA_NAME: "fedora-33"
    UBUNTU_NAME: "ubuntu-2104"
    PRIOR_UBUNTU_NAME: "ubuntu-2010"

    # Google-cloud VM Images
    IMAGE_SUFFIX: "c6032583541653504"
    FEDORA_CACHE_IMAGE_NAME: "fedora-${IMAGE_SUFFIX}"
    PRIOR_FEDORA_CACHE_IMAGE_NAME: "prior-fedora-${IMAGE_SUFFIX}"
    UBUNTU_CACHE_IMAGE_NAME: "ubuntu-${IMAGE_SUFFIX}"
    PRIOR_UBUNTU_CACHE_IMAGE_NAME: "prior-ubuntu-${IMAGE_SUFFIX}"

    # Container FQIN's
    FEDORA_CONTAINER_FQIN: "quay.io/libpod/fedora_podman:${IMAGE_SUFFIX}"
    PRIOR_FEDORA_CONTAINER_FQIN: "quay.io/libpod/prior-fedora_podman:${IMAGE_SUFFIX}"
    UBUNTU_CONTAINER_FQIN: "quay.io/libpod/ubuntu_podman:${IMAGE_SUFFIX}"
    PRIOR_UBUNTU_CONTAINER_FQIN: "quay.io/libpod/prior-ubuntu_podman:${IMAGE_SUFFIX}"


gcp_credentials: ENCRYPTED[0c639039cdd3a9a93fac7746ea1bf366d432e5ff3303bf293e64a7ff38dee85fd445f71625fa5626dc438be2b8efe939]


# Default VM to use unless set or modified by task
gce_instance:
    image_project: "libpod-218412"
    zone: "us-central1-c"  # Required by Cirrus for the time being
    cpu: 2
    memory: "4Gb"
    disk: 200  # Required for performance reasons
    image_name: "${FEDORA_CACHE_IMAGE_NAME}"


# This task is critical.  It updates the "last-used by" timestamp stored
# in metadata for all VM images.  This mechanism functions in tandem with
# an out-of-band pruning operation to remove disused VM images.
meta_task:
    alias: meta
    name: "VM img. keepalive"

    # see bors.toml
    skip: $CIRRUS_BRANCH =~ ".*\.tmp"

    container: &smallcontainer
        image: "quay.io/libpod/imgts:$IMAGE_SUFFIX"
        cpu: 1
        memory: 1

    env:
        IMGNAMES: >-
            ${FEDORA_CACHE_IMAGE_NAME}
            ${PRIOR_FEDORA_CACHE_IMAGE_NAME}
            ${UBUNTU_CACHE_IMAGE_NAME}
            ${PRIOR_UBUNTU_CACHE_IMAGE_NAME}
        BUILDID: "${CIRRUS_BUILD_ID}"
        REPOREF: "${CIRRUS_REPO_NAME}"
        GCPJSON: ENCRYPTED[e8a53772eff6e86bf6b99107b6e6ee3216e2ca00c36252ae3bd8cb29d9b903ffb2e1a1322ea810ca251b04f833b8f8d9]
        GCPNAME: ENCRYPTED[fb878daf188d35c2ed356dc777267d99b59863ff3abf0c41199d562fca50ba0668fdb0d87e109c9eaa2a635d2825feed]
        GCPPROJECT: "libpod-218412"

    clone_script: &noop mkdir -p $CIRRUS_WORKING_DIR
    script: /usr/local/bin/entrypoint.sh


gating_task:
    name: "Gating test"
    alias: gating

    # Only run this on PRs, never during post-merge testing.  This is also required
    # for proper setting of EPOCH_TEST_COMMIT value, required by validation tools.
    only_if: $CIRRUS_PR != ""

    # see bors.toml
    skip: $CIRRUS_BRANCH =~ ".*\.tmp"

    # Runs within Cirrus's "community cluster"
    container:
        image: "$FEDORA_CONTAINER_FQIN"
        cpu: 4
        memory: 12

    timeout_in: 20m

    script:
        - export PATH="$PATH:$GOPATH/bin"
        - make
        - go get github.com/vbatts/git-validation
        - make validate

test_task:
    name: "Test on $FEDORA_NAME"
    alias: test

    # see bors.toml
    skip: $CIRRUS_BRANCH =~ ".*\.tmp"

    depends_on:
        - gating

    script:
        - "$SCRIPT_BASE/latest_podman.sh"
        - "$SCRIPT_BASE/test.sh"


# Status aggregator for all tests.  This task simply ensures a defined
# set of tasks all passed, and allows confirming that based on the status
# of this task.
success_task:
    name: "Total Success"
    alias: success

    # see bors.toml
    skip: $CIRRUS_BRANCH =~ ".*\.tmp"

    # N/B: ALL tasks must be listed here, minus their '_task' suffix.
    depends_on:
        - meta
        - gating
        - test
    container: *smallcontainer
    clone_script: *noop
    script: *noop
