[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ["py36"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
[tool.isort]
profile = "black"
line_length = 100

